### ISSUE TITLE
Request: Allow overriding onDrop events

### ISSUE THREAD

**Issue by KeithScheiwiller** [helion3/inspire-tree-dom#7]
It'd be very beneficial if there were functionality in place to allow the developer to replace the implementation of `onDrop` on nodes. By doing so it would be possible to for instance not allow drops on an incompatible node, etc.

It looks like it would be fairly easy to replace `TreeDom.__proto__.onDrop`, but I could not find a clean way to access the `onDrop` method of `<li>`s.

**Comment by viveleroi** [comment]
I've actually been planning support for a way to validate drop target nodes. Internally this is already done when ensuring a target node is not a child of the dragged node. I haven't done any work yet because I'm not quite sure how I want to handle it.

I'd prefer a way to "disable" invalid drop targets the moment a node is picked up, but for users with large datasets that's problematic. Yet I would also prefer to validate a target node *once* rather every dragover, so either I can do it for all nodes on dragstart or cache/debounce the call for dragover, or both, and let users choose which method.

Regarding overloading internal methods, there isn't a way to do it because the `ListItem` renderer gets compiled as a private-scope "module" and there is no way to access it without either altering source or modifying it post-compilation (i.e. editing the `dist/inspire-tree-dom.js` file directly).

I eventually want to look into a plugin architecture that would allow this, but once I push work validating nodes it sounds like your use-case will be taken care of?

**Comment by KeithScheiwiller** [comment]
Ah ya, it would make more sense to do it on dragstart.
As long as it's possible to choose valid drop targets based on the properties of the node being dragged, that should work fine!

**Comment by viveleroi** [comment]
You can do this now with v4. You can provide a custom validator, you can control whether you validate drag targets on dragstart or dragover, etc.
